# Linear Regression to Predict Titanic Passenger Age

**Deep Dive Coding Data Science Bootcamp Sample Project**

---
Robert Citek - October 5th, 2026

## Problem Definition

State the business problem. Translate the business problem into a Data Science problem by stating what kind of problem it is ( supervised vs unsupervised ) and whether it is a classification, regression, or clustering problem.  Mention which model will be used, if known.

### Regression

For a regression, the Age will be the target.

## Data Collection/Sources

### Data Overview

This data comes from [Kaggle](https://www.kaggle.com/c/titanic/data), which was then copied to AWS for easy access.

https://ddc-datascience.s3.amazonaws.com/Projects/Example/Data/Titanic.train.csv

### Imports

In [1]:
from IPython.display import Image
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns

from sklearn import datasets, metrics, model_selection
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

### File Paths

Create a variable `url` that contains the web link to the CSV data

In [2]:
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Example/Data/Titanic.train.csv'    # insert url here
url

'https://ddc-datascience.s3.amazonaws.com/Projects/Example/Data/Titanic.train.csv'

### Load data

Load the data into a data frame named `titanic_df`.

In [3]:
# load data
titanic_df= pd.read_csv(url)

### head

Look at the first few rows

In [ ]:
# first few rows
titanic_df.head()

### tail

Look at the last few rows

In [ ]:
# last few rows
titanic_df.tail()

### shape

In [ ]:
# shape of data frame
titanic_df.shape

### size

In [ ]:
# size of data frame
titanic_df.size

### Summary meta-data

Run the `info()` method on the data frame.

In [ ]:
# display meta-data
titanic_df.info()

### Summary statistics

Summary statistics give you a quick overview of the data.  Some items to spot check:
- the Target:
  - look for nulls
    - null will be culled
  - look at min, max, median, and mean
    - is it a categorical field masquerading as a number?
- the Features:
  - numerical
    - look at min, max, median, and mean
      - a min=1 and max=count suggests an ID
  - categorical
    - look at unique and freq
      - freq=1, unique=count suggests an ID
      - freq=count suggests a meaningless feature

Run the `describe()` method on the data frame.

In [ ]:
# display summary statistics
titanic_df.describe()

### target nulls

The target should be the first field that you look at.  Its data type will tell you what kind of machine learning problem this is ( classification or regression. ) Any nulls should be culled.  You can check for any skew in the data set.

In [4]:
# look for nulls in the target
titanic_df['Survived'].value_counts(dropna=False)

Survived
0    549
1    342
Name: count, dtype: int64

### Nulls

In [5]:
# look for nulls
titanic_df.isnull().sum().sort_values(ascending=False)

Cabin          687
Age            177
Embarked         2
PassengerId      0
Name             0
Pclass           0
Survived         0
Sex              0
Parch            0
SibSp            0
Fare             0
Ticket           0
dtype: int64

In [6]:
# look for nulls, displaying relative frequency
null_sum= titanic_df.isnull().sum()
null_freq= null_sum/titanic_df.shape[0]*100
null_freq.sort_values()

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Embarked        0.224467
Age            19.865320
Cabin          77.104377
dtype: float64

### dtypes - column data types

Which data types would be appropriate for Linear Regression?

In [7]:
# display data types
titanic_df.dtypes.sort_values()

PassengerId      int64
Survived         int64
Pclass           int64
SibSp            int64
Parch            int64
Age            float64
Fare           float64
Name            object
Sex             object
Ticket          object
Cabin           object
Embarked        object
dtype: object

### Unique elements

If the total number of unique items in a field equals the number of rows, that suggests those fields are unique IDs ( e.g. names, IDs ) and should be dropped.

In [8]:
# number of unique elements in a column
titanic_df.nunique().sort_values(ascending=False)

PassengerId    891
Name           891
Ticket         681
Fare           248
Cabin          147
Age             88
SibSp            7
Parch            7
Embarked         3
Pclass           3
Survived         2
Sex              2
dtype: int64

## Data Cleaning

### Backup #1

In [ ]:
# make backup
titanic_df_backup= titanic_df.copy()

In [ ]:
# restore from backup
titanic_df = titanic_df_backup.copy()

### Keep only the target and two features

Select `Age` for the target and `Fare` for the feature

In [10]:
# select the target and one feature
titanic_df_age_fare = titanic_df[['Age','Fare']]
titanic_df_age_fare.head()

    Age     Fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500

### Backup #2

In [ ]:
# make backup
titanic_df_age_fare_backup = titanic_df_age_fare.copy()

In [ ]:
# restore from backup
titanic_df_age_fare_backup = titanic_df_age_fare_backup.copy()

### Address any rows with nulls

- If the number of nulls in a column is low, it would be easiest to drop the row.
- If the number of nulls in a column is high, it would be easiest to drop the column.
- If the number of nulls in a column is between the low and high, one should impute values for the nulls.

#### Impute

In [11]:
# counts the nulls in age and fare
titanic_df_age_fare.isnull().sum().sort_values (ascending=False)

Age     177
Fare      0
dtype: int64

In [12]:
# drop the nulls values in Age
titanic_df_age_fare = titanic_df_age_fare.dropna(subset=['Age'])

In [13]:
# verify nulls values in Age
titanic_df_age_fare.isnull().sum()

Age     0
Fare    0
dtype: int64

Impute with the median.

In [ ]:
# Calculate the median

In [ ]:
# Assign median to nulls

In [ ]:
# Verify there are no nulls

In [ ]:
# Verify median is about the same as before

## Exploratory Data Analysis

Linear Regression has two requirements:
1. the features are correlated with the target
1. the features are not correlated with each other

### correlated with the target

In [ ]:
# Calculate a correlation matrix for the target

In [ ]:
# Display the correlation matrix

In [ ]:
# Create a data series with features ranked by correlation

### independence of features: correlation

In [ ]:
# Calculate a correlation matrix for the features

In [ ]:
# Display the correlation matrix

In [ ]:
# Create a data series with features ranked by correlation

## Processing

### Prepare data frame

In [ ]:
# Split data frame into target and features

In [ ]:
# Verify features

In [ ]:
# Verify target

### Multiple Cross Validation ( CV )

Create a CV loop with 100 iterations.  Capture performance metric in an array names `results`.
Use accuracy for the performance metric.

In [ ]:
# Multiple CV loop

#### Performance

We'll use RMSE as our performance metric.

In [ ]:
# Calculate mean of results

In [ ]:
# Display a histogram of the results

## Communication of Results

Conclusion:

Future work: