# Naive Bayes Classification to Predict Titanic Survival

**Deep Dive Coding Data Science Bootcamp Sample Project**

---
Robert Citek - October 5th, 2026

## Problem Definition

State the business problem. Translate the business problem into a Data Science problem by stating what kind of problem it is ( supervised vs unsupervised ) and whether it is a classification, regression, or clustering problem.  Mention which model will be used, if known.

## Data Collection/Sources

### Data Overview

This data comes from [Kaggle](https://www.kaggle.com/c/titanic/data), which was then copied to AWS for easy access.

https://ddc-datascience.s3.amazonaws.com/Projects/Example/Data/Titanic.train.csv

### Imports

In [2]:
from IPython.display import Image
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns

from sklearn import datasets, metrics, model_selection
from sklearn import model_selection
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

### File Paths

Create a variable `url` that contains the web link to the CSV data

In [9]:
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Example/Data/Titanic.train.csv'  # insert url here
url

'https://ddc-datascience.s3.amazonaws.com/Projects/Example/Data/Titanic.train.csv'

### Load data

Load the data into a data frame named `titanic_df`.

In [10]:
# load data
titanic_df = pd.read_csv( url )

### head

Look at the first few rows

In [11]:
# first few rows
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### tail

Look at the last few rows

In [16]:
# last few rows
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

### shape

In [15]:
# shape of data frame
titanic_df.shape  #output: display (row,column)

(891, 12)

### size

In [17]:
# size of data frame
titanic_df.size   #output: calculate the number of rows multiplied by the nuber of columns

10692

### Summary meta-data

Run the `info()` method on the data frame.

In [18]:
# display meta-data
titanic_df.info()

# display show:
#total rows= 891
#total colun=12
#non-null count= show which columns have missing data by reporting( anything less than 891)
#data type= int(whole number),float(decimal number), object(text string or mixed data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

### Summary statistics

Summary statistics give you a quick overview of the data.  Some items to spot check:
- the Target:
  - look for nulls
    - null will be culled
  - look at min, max, median, and mean
    - is it a categorical field masquerading as a number?
- the Features:
  - numerical
    - look at min, max, median, and mean
      - a min=1 and max=count suggests an ID
  - categorical
    - look at unique and freq
      - freq=1, unique=count suggests an ID
      - freq=count suggests a meaningless feature

Run the `describe()` method on the data frame.

In [19]:
# display summary statistics
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

### target value_counts()

The target should be the first field that you look at.  Its data type will tell you what kind of machine learning problem this is ( classification or regression. ) Any nulls should be culled.  You can check for any skew in the data set.

In [23]:
# value_counts on target ; include nulls
titanic_df['Survived'].value_counts( dropna = False )

#value_counts, count all the row but skip blank rows
#dropna = false, blank rows are counted

#output shows
#0-> passenger who died
#1-> passenger who survived, #1 usually mean yes
# since the output onluy have 2 valvues-> this is classigication

Survived
0    549
1    342
Name: count, dtype: int64

In [24]:
# normalized value_counts on target ; include nulls
titanic_df['Survived'].value_counts( normalize = True , dropna = False ) * 100

# normalize = True, take the count and divided by the total amount of rows
# ex. 549/ 891 & 342/891.

Survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

### Nulls

In [28]:
# look for nulls
titanic_df.isnull().sum()

#.isnull, this look at the table and ask if the cell blank, true of false
#.sum(), add up the column with the blanks(True)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [30]:
# look for nulls, displaying relative frequency
null_sum = titanic_df.isnull().sum()
null_freq = null_sum / titanic_df.shape[0] * 100
#.shape give (rows,columns)but [0]pick the first number
null_freq.sort_values()

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Embarked        0.224467
Age            19.865320
Cabin          77.104377
dtype: float64

### dtypes - column data types

Which data types would be appropriate for Gaussian Naive Bayes?

In [ ]:
# display data types

### Unique elements

If the total number of unique items in a field equals the number of rows, that suggests those fields are unique IDs ( e.g. names, IDs ) and should be dropped.

In [ ]:
# number of unique elements in a column

## Data Cleaning

### Backup #1

In [ ]:
# make backup

In [ ]:
# restore from backup

### Keep only the target and one feature

Select `Survived` for the target and `Age` for the single feature

In [ ]:
# select the target and one feature

### Backup #2

In [ ]:
# make backup

In [ ]:
# restore from backup

### Address any rows with nulls

- If the number of nulls in a column is low, it would be easiest to drop the row.
- If the number of nulls in a column is high, it would be easiest to drop the column.
- If the number of nulls in a column is between the low and high, one should impute values for the nulls.

#### Impute

Impute with the median.

In [ ]:
# Calculate the median

In [ ]:
# Assign median to nulls

In [ ]:
# Verify there are no nulls

In [ ]:
# Verify median is about the same as before

## Exploratory Data Analysis

GNB has two requirements:
1. the features are normally distributed
1. the features are not correlated with each other

### normal distribution of features: histogram

In [ ]:
# Display a histogram

### no correlation with single feature

## Processing

In [ ]:
# Split data frame into target and features

In [ ]:
# Verify features

In [ ]:
# Verify target

### Single Cross Validation ( CV )

Run a single Cross Validation

#### Train Test Split

In [ ]:
# Train Test Split

In [ ]:
# Verify shape of each data set from Train Test Split

#### Model

In [ ]:
# Create an empty GNB model

#### Fit

In [ ]:
# Train ( fit ) the model

#### Prediction

In [ ]:
# Make predicitons using the model

#### Performance

We'll meassure accuracy, which is the proportions of the number correctly predicted, which is mathematically the same as one minus the proportion incorrectly predicted.

In [ ]:
# Calculate the accuracy

In [ ]:
# Display a confusion matrix

### Multiple Cross Validation ( CV )

Create a CV loop with 100 iterations.  Capture performance metric in an array names `results`.
Use accuracy for the performance metric.

In [ ]:
# Multiple CV loop

In [ ]:
# Calculate mean of results

In [ ]:
# Display a confusion matrix

In [ ]:
# Display a histogram of the results

## Communication of Results

Conclusion:

Future work: