# Project Title

## Problem Definition

State the business problem. Translate the business problem into a Data Science problem by stating what kind of problem it is ( supervised vs unsupervised ) and whether it is a classification, regression, or clustering problem.

## Data Collection/Sources

In [16]:
#import from IPython.display import Image
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import plotly.express as px
import seaborn as sns

from sklearn import datasets, metrics, model_selection
from sklearn import model_selection
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [17]:
# file name
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Project.2-Housing/Data/Housing.Data.csv'

In [18]:
#load data
house_df= pd.read_csv(url,
               usecols= ['Lot Frontage','SalePrice'])

In [19]:
# look at first and last few rows
print(house_df.head())
print(house_df.tail())

   Lot Frontage  SalePrice
0          62.0     115400
1          72.0      90000
2          50.0     141000
3          68.0     254000
4          60.0     155000
      Lot Frontage  SalePrice
2632          52.0     114500
2633          74.0     162000
2634          61.0     211500
2635          78.0     165000
2636          41.0     225000

In [20]:
# look at shape and size

print(house_df.shape)
print(house_df.size)

(2637, 2)
5274

In [21]:
# display meta data (info)
house_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2637 entries, 0 to 2636
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Lot Frontage  2188 non-null   float64
 1   SalePrice     2637 non-null   int64
dtypes: float64(1), int64(1)
memory usage: 41.3 KB

In [22]:
# display summary statistics
house_df.describe()

       Lot Frontage      SalePrice
count   2188.000000    2637.000000
mean      69.166819  179986.230186
std       23.356779   78309.251522
min       21.000000   12789.000000
25%       58.000000  129500.000000
50%       68.000000  160000.000000
75%       80.000000  213000.000000
max      313.000000  745000.000000

In [27]:
# Columns data types

house_df.dtypes.sort_values()

SalePrice         int64
Lot Frontage    float64
dtype: object

In [26]:
# look for how the often a value appears
house_df['SalePrice'].value_counts(dropna=False)

SalePrice
140000    31
135000    30
130000    28
155000    24
160000    22
          ..
160200     1
174190     1
415298     1
118400     1
232600     1
Name: count, Length: 983, dtype: int64

In [24]:
# look for nulls in target and features
house_df.isnull().sum().sort_values(ascending=False)

Lot Frontage    449
SalePrice         0
dtype: int64

## Data Cleaning

## Exploratory Data Analysis

## Processing

## Data Visualization/Communication of Results